"use client"

import React from 'react'
import { AlertCircle, Clock, Shield } from 'lucide-react'

const mockAlerts = [
  { id: 1, title: 'Unauthorized Login Attempt', node: 'Edge-Server-01', time: '2 mins ago', level: 'HIGH' },
  { id: 2, title: 'Suspicious File Transfer', node: 'Workstation-42', time: '15 mins ago', level: 'MEDIUM' },
  { id: 3, title: 'Database Query Anomaly', node: 'SQL-Primary', time: '1 hour ago', level: 'LOW' },
]

export default function AlertsPage() {
  return (
    <div className="space-y-8 animate-in fade-in duration-500">
      <div>
        <h1 className="text-3xl font-bold text-accent">Security Alerts</h1>
        <p className="text-foreground/50 mt-1">Real-time alerts generated by AI agents.</p>
      </div>

      <div className="space-y-4">
        {mockAlerts.map((alert) => (
          <div key={alert.id} className="glass p-6 flex items-center justify-between group hover:border-accent/30 transition-all">
            <div className="flex items-center gap-4">
              <div className="p-3 bg-white/5 rounded-xl">
                <AlertCircle className={`w-6 h-6 ${alert.level === 'HIGH' ? 'text-red-500' : 'text-yellow-500'}`} />
              </div>
              <div>
                <h3 className="font-bold">{alert.title}</h3>
                <div className="flex gap-4 mt-1 text-xs text-foreground/40">
                  <span className="flex items-center gap-1"><Shield className="w-3 h-3" /> {alert.node}</span>
                  <span className="flex items-center gap-1"><Clock className="w-3 h-3" /> {alert.time}</span>
                </div>
              </div>
            </div>
            <button className="px-4 py-2 text-xs font-bold border border-accent/20 rounded-lg group-hover:bg-accent group-hover:text-primary transition-all">
              REVIEW THREAD
            </button>
          </div>
        ))}
      </div>
    </div>
  )
}
